### PR TITLE
Get error while "An existing user is trying to log in using an alread…

### PR DESCRIPTION
**Pull request by w-site**
…y connected passport." #128

### CODE REVIEW

**Comment by fenichelar** [comment]
Can we get this approved?

**Comment by w-site** [comment]
Approver of what ? Show you error when i try to do this. For example. Passport model isn't populate to user model so you can't get passport.user.id

**Comment by fenichelar** [comment]
I meant accept the pull request. Thanks for making the fix.

**Comment by w-site** [comment]
I haven't "write access" to do this. Or i didn't understand about what "accept" the pull request you talking about.

**Comment by fenichelar** [comment]
I know. I wasn't referring to you :)

**Comment by w-site** [comment]
Sorry for the misunderstanding, this is my mistake.

**Comment by fenichelar** [comment]
No worries. I couldn't figure out how to fix the problem, you got it working. Works flawlessly!

**Comment by jials** [comment]
This fix makes it work again! Thanks!

**Comment by basert** [comment]
Please merge this fix, thanks :)

**Comment by basert** [comment]
Wow, thanks for the fast merge, can you create a new npm version aswell? When I specify the github repo by hand, the dist folder does not exist and starting the app fails with:
`Error: Cannot find module '...node_modules/sails-auth'] code: 'MODULE_NOT_FOUND'`

**Comment by tjwebb** [comment]
You likely will need to run `npm install` inside the repo first to run the build

**Comment by kiel-cristian** [comment]
@tjwebb Waiting also for new npm version aswell, please!

Great work with this package, it saves me a lot of working time :)

**Comment by ahmadao** [comment]
I still get this error after logging out, then logging in again.

**Comment by ahmadao** [comment]
The list inside the package.json points to a tarball that doesn't contain the latest version. How can we fix this?

**Comment by ahmadao** [comment]
The nam version is older than the git version. How can we get the latest version?

**Comment by anabelle** [comment]
+1

**Pull request merged**
